name: Create Milestone with tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  set-milestone:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Set tag'
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: 'Check tag'
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}

      - name: 'Create new milestone'
        id: createmilestone
        uses: "WyriHaximus/github-action-create-milestone@v1"
        with:
          title:  ${{ steps.vars.outputs.tag }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
